// Dados de insumos importados da planilha (aba MATRIZ DE DADOS)
// Gerado automaticamente - usado apenas na primeira execucao do app
const SEED_INSUMOS = [
  { nome: 'ABSOLUT 1L', categoria: 'Vodka', casa: 'JT - FORTUNATO', fornecedor: 'SPON', unidade_compra: 'ml', tamanho_unidade: 1000, preco_compra: 54.9, data_atualizacao: '27/07' },
  { nome: 'ACEROLA POLPA', categoria: 'Suco', casa: 'JT - FORTUNATO', fornecedor: 'BABYFRUIT', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 0, data_atualizacao: '27/07' },
  { nome: 'ACETO BALSAMICO 500ML', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'AVELINOS', unidade_compra: 'ml', tamanho_unidade: 500, preco_compra: 12.9, data_atualizacao: '27/07' },
  { nome: 'ACUCAR REFINADO', categoria: 'Outros', casa: 'VMB - OLIVIO', fornecedor: 'KINGFOOD', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 2.59, data_atualizacao: '27/07' },
  { nome: 'AGUA DE COCO 1L', categoria: 'Água', casa: 'VMB - OLIVIO', fornecedor: 'FG7 (PERNOD)', unidade_compra: 'ml', tamanho_unidade: 1000, preco_compra: 12.84, data_atualizacao: '27/07' },
  { nome: 'AGUA MINERAL COM GAS', categoria: 'Água', casa: 'ESCRITORIO', fornecedor: 'MALTE', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 1.89, data_atualizacao: '28/07' },
  { nome: 'AGUA SANITARIA 5L', categoria: 'Água', casa: 'JT - FORTUNATO', fornecedor: 'Quality', unidade_compra: 'ml', tamanho_unidade: 5000, preco_compra: 12.9, data_atualizacao: '27/07' },
  { nome: 'AGUA SAO LOURENCO COM GAS', categoria: 'Água', casa: 'VMB - OLIVIO', fornecedor: 'SOS', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 2.48, data_atualizacao: '28/07' },
  { nome: 'AGUA SAO LOURENCO SEM GAS', categoria: 'Água', casa: 'VMB - OLIVIO', fornecedor: 'SOS', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 2.27, data_atualizacao: '28/07' },
  { nome: 'ALCAPARRAS BALDE 2KG', categoria: 'Outros', casa: 'JT - FORTUNATO', fornecedor: 'KINGFOOD', unidade_compra: 'g', tamanho_unidade: 2000, preco_compra: 77.87, data_atualizacao: '27/07' },
  { nome: 'ALCOOL 70% L', categoria: 'Limpeza', casa: 'VMB - OLIVIO', fornecedor: 'Quality', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 7.2, data_atualizacao: '27/07' },
  { nome: 'ALCOOL GEL', categoria: 'Limpeza', casa: 'JT - FORTUNATO', fornecedor: 'Quality', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 9, data_atualizacao: '27/07' },
  { nome: 'AMIDO DE MILHO EM PO', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'DTK', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 5.47, data_atualizacao: '27/07' },
  { nome: 'AMSTEL ULTRA SEM GLUTEN 275ML', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'HNK', unidade_compra: 'ml', tamanho_unidade: 275, preco_compra: 5.23, data_atualizacao: '27/07' },
  { nome: 'ANEL DE CEBOLA CONGELADO KG', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'MULTIFOODS', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 16.69, data_atualizacao: '27/07' },
  { nome: 'APEROL 750 ML', categoria: 'Licor/Aperitivo', casa: 'JT - FORTUNATO', fornecedor: 'MDG (PERNOD)', unidade_compra: 'ml', tamanho_unidade: 750, preco_compra: 46.91, data_atualizacao: '27/07' },
  { nome: 'ARROZ ARBORIO CAMIL KG', categoria: 'Outros', casa: 'VMB - OLIVIO', fornecedor: 'KINGFOOD', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 14.42, data_atualizacao: '27/07' },
  { nome: 'ARROZ TIPO1 5 KG CAMIL', categoria: 'Outros', casa: 'VMB - OLIVIO', fornecedor: 'DTK', unidade_compra: 'g', tamanho_unidade: 5000, preco_compra: 4.29, data_atualizacao: '27/07' },
  { nome: 'AZEITE EXTRA VIRGEM 5L GALLO', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'MULTIFOODS', unidade_compra: 'ml', tamanho_unidade: 5000, preco_compra: 252.99, data_atualizacao: '27/07' },
  { nome: 'AZEITE TRUFADO 250ML', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'EMPORIO TARTUFI', unidade_compra: 'ml', tamanho_unidade: 250, preco_compra: 64.9, data_atualizacao: '27/07' },
  { nome: 'BACARDI CARTA BLANCA 980 ML', categoria: 'Rum', casa: 'JT - FORTUNATO', fornecedor: 'SPON', unidade_compra: 'ml', tamanho_unidade: 980, preco_compra: 32.9, data_atualizacao: '27/07' },
  { nome: 'BAGUETE TRADICIONAL FABRIQUE', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'FABRIQUE', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 0, data_atualizacao: '27/07' },
  { nome: 'BATATA CANOA CONGELADA MCCAIN', categoria: 'Outros', casa: 'JT - FORTUNATO', fornecedor: 'MEGA G', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 21.24, data_atualizacao: '27/07' },
  { nome: 'BATATA PALHA YOKI', categoria: 'Outros', casa: 'JT - FORTUNATO', fornecedor: 'MEGA G', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 8.25, data_atualizacao: '27/07' },
  { nome: 'BATATA PALITO 7MM MCCAIN SURECRSIP', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'MEGA G', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 15.69, data_atualizacao: '27/07' },
  { nome: 'BISTECA CORINGA', categoria: 'Outros', casa: 'JT - FORTUNATO', fornecedor: 'CORINGA', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 17.99, data_atualizacao: '27/07' },
  { nome: 'BOM AR SPRAY', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'Quality', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 10.9, data_atualizacao: '27/07' },
  { nome: 'BOMBOM DE ALCATRA', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'MINERVA', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 62, data_atualizacao: '27/07' },
  { nome: 'BOMBRIL  LA DE ACO', categoria: 'Outros', casa: 'JT - FORTUNATO', fornecedor: 'Quality', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 2.5, data_atualizacao: '27/07' },
  { nome: 'CACAU EM PO SICAO100% 500G', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'DTK', unidade_compra: 'g', tamanho_unidade: 500, preco_compra: 45.8, data_atualizacao: '27/07' },
  { nome: 'CAMARAO CINZA - DESCASCADO E EVISCERADO - 80/100', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'PEIXE GOURMET', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 0, data_atualizacao: '27/07' },
  { nome: 'CAMPARI 998 ML', categoria: 'Licor/Aperitivo', casa: 'JT - FORTUNATO', fornecedor: 'MDG (PERNOD)', unidade_compra: 'ml', tamanho_unidade: 998, preco_compra: 57.38, data_atualizacao: '27/07' },
  { nome: 'CANUDO EMBALADO', categoria: 'Descartáveis', casa: 'MF - BETSY', fornecedor: 'DISTUDO', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 0, data_atualizacao: '27/07' },
  { nome: 'CANUDO MILKSHAKE', categoria: 'Descartáveis', casa: 'MF - BETSY', fornecedor: 'DISTUDO', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 0, data_atualizacao: '27/07' },
  { nome: 'CAPSULA TRES AMENO', categoria: 'Café', casa: 'JT - FORTUNATO', fornecedor: '3 CORAÇÕES', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 1.79, data_atualizacao: '27/07' },
  { nome: 'CARNE SECA ( JERKED BEEF )', categoria: 'Outros', casa: 'JT - FORTUNATO', fornecedor: 'CORINGA', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 47.96, data_atualizacao: '27/07' },
  { nome: 'CASTANHA DO PARA', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'KINGFOOD', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 73.52, data_atualizacao: '27/07' },
  { nome: 'CATCHUP HEINZ 397G', categoria: 'Outros', casa: 'VMB - OLIVIO', fornecedor: 'DTK', unidade_compra: 'g', tamanho_unidade: 397, preco_compra: 10.99, data_atualizacao: '27/07' },
  { nome: 'CEREJA AMARENA', categoria: 'Outros', casa: 'JT - FORTUNATO', fornecedor: 'FG7 (PERNOD)', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 399.93, data_atualizacao: '27/07' },
  { nome: 'CERVEJA BLUE MOON 355ML', categoria: 'Cerveja', casa: 'MF - BETSY', fornecedor: 'HNK', unidade_compra: 'ml', tamanho_unidade: 355, preco_compra: 9.46, data_atualizacao: '27/07' },
  { nome: 'CERVEJA THEREZOPOLIS DUNKEL 500ML', categoria: 'Cerveja', casa: 'MF - BETSY', fornecedor: 'SPAL/FEMSA', unidade_compra: 'ml', tamanho_unidade: 500, preco_compra: 8, data_atualizacao: '27/07' },
  { nome: 'CHA FEEL GOOD PITAYA', categoria: 'Outros', casa: 'ESCRITORIO', fornecedor: 'FOOD CENTER ALIMENTOS', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 5.19, data_atualizacao: '29/07' },
  { nome: 'CHA YAI FRUTAS VERMELHAS', categoria: 'Hortifruti', casa: 'ESCRITORIO', fornecedor: 'FOOD CENTER ALIMENTOS', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 4.19, data_atualizacao: '29/07' },
  { nome: 'CHA YAI JABUTICABA', categoria: 'Outros', casa: 'ESCRITORIO', fornecedor: 'FOOD CENTER ALIMENTOS', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 4.19, data_atualizacao: '29/07' },
  { nome: 'CHANTILLY NORCAU 1L', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'SANTA VITA', unidade_compra: 'ml', tamanho_unidade: 1000, preco_compra: 0, data_atualizacao: '27/07' },
  { nome: 'CHEDDAR BISNAGA SCALA 1,5', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'MULTIFOODS', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 52.99, data_atualizacao: '27/07' },
  { nome: 'CHEDDAR PROCESSADO JAMMY', categoria: 'Outros', casa: 'VMB - OLIVIO', fornecedor: 'MULTIFOODS', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 35.29, data_atualizacao: '27/07' },
  { nome: 'CHIFERI ELBOWS 500G', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'DTK', unidade_compra: 'g', tamanho_unidade: 500, preco_compra: 10.89, data_atualizacao: '27/07' },
  { nome: 'CHOCOLATE AO LEITE BARRA 2,1', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'MEGA G', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 134.77, data_atualizacao: '27/07' },
  { nome: 'CHOCOLATE BRANCO BARRA 2,1', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'MEGA G', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 180.95, data_atualizacao: '27/07' },
  { nome: 'CHOCOLATE MEIO AMARGO BARRA 2,1', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'MEGA G', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 153.01, data_atualizacao: '27/07' },
  { nome: 'CHOPP BRAHMA BLACK 30L', categoria: 'Cerveja', casa: 'JT - FORTUNATO', fornecedor: 'AMBEV', unidade_compra: 'ml', tamanho_unidade: 30000, preco_compra: 14.08, data_atualizacao: '27/07' },
  { nome: 'CHOPP BRAHMA CLARO 50L', categoria: 'Cerveja', casa: 'JT - FORTUNATO', fornecedor: 'AMBEV', unidade_compra: 'ml', tamanho_unidade: 50000, preco_compra: 14.45, data_atualizacao: '27/07' },
  { nome: 'CHOPP COLORADO APPIA 30L', categoria: 'Cerveja', casa: 'JT - FORTUNATO', fornecedor: 'AMBEV', unidade_compra: 'ml', tamanho_unidade: 30000, preco_compra: 15.12, data_atualizacao: '27/07' },
  { nome: 'CHOPP HEINEKEN BARRIL 30L', categoria: 'Cerveja', casa: 'MF - BETSY', fornecedor: 'HNK', unidade_compra: 'ml', tamanho_unidade: 30000, preco_compra: 15.32, data_atualizacao: '27/07' },
  { nome: 'CHOPP STELLA ARTOIS 30L', categoria: 'Cerveja', casa: 'JT - FORTUNATO', fornecedor: 'AMBEV', unidade_compra: 'ml', tamanho_unidade: 30000, preco_compra: 14.08, data_atualizacao: '27/07' },
  { nome: 'CHURROS CORACAO PC 18UN', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'CHUCRE', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 0, data_atualizacao: '27/07' },
  { nome: 'CINZANO 1757 1L', categoria: 'Outros', casa: 'JT - FORTUNATO', fornecedor: 'FG7 (PERNOD)', unidade_compra: 'ml', tamanho_unidade: 1000, preco_compra: 126.41, data_atualizacao: '27/07' },
  { nome: 'CIROC REDBERRY 750 ML', categoria: 'Outros', casa: 'JT - FORTUNATO', fornecedor: 'GENIUS/OFF/EASY/SKY', unidade_compra: 'ml', tamanho_unidade: 750, preco_compra: 189.9, data_atualizacao: '27/07' },
  { nome: 'COCA COLA 250ML VIDRO', categoria: 'Refrigerante', casa: 'MF - BETSY', fornecedor: 'SPAL/FEMSA', unidade_compra: 'ml', tamanho_unidade: 250, preco_compra: 3.45, data_atualizacao: '27/07' },
  { nome: 'COCA COLA LATA', categoria: 'Refrigerante', casa: 'ESCRITORIO', fornecedor: 'MALTE', unidade_compra: 'ml', tamanho_unidade: 350, preco_compra: 3.49, data_atualizacao: '28/07' },
  { nome: 'COCA COLA ZERO LATA', categoria: 'Refrigerante', casa: 'ESCRITORIO', fornecedor: 'MALTE', unidade_compra: 'ml', tamanho_unidade: 350, preco_compra: 3.59, data_atualizacao: '28/07' },
  { nome: 'COCA COLA ZERO VIDRO 250 ML', categoria: 'Refrigerante', casa: 'VMB - OLIVIO', fornecedor: 'SPAL/FEMSA', unidade_compra: 'ml', tamanho_unidade: 250, preco_compra: 3.45, data_atualizacao: '27/07' },
  { nome: 'COCO RALADO SEM ACUCAR  KG', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'KINGFOOD', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 19.75, data_atualizacao: '27/07' },
  { nome: 'COLORADO APPIA 600ML', categoria: 'Cerveja', casa: 'JT - FORTUNATO', fornecedor: 'AMBEV', unidade_compra: 'ml', tamanho_unidade: 600, preco_compra: 0, data_atualizacao: '27/07' },
  { nome: 'COPO DESCARTAVEL 300ML', categoria: 'Descartáveis', casa: 'JT - FORTUNATO', fornecedor: 'Quality', unidade_compra: 'ml', tamanho_unidade: 300, preco_compra: 0, data_atualizacao: '27/07' },
  { nome: 'COPO DESCARTAVEL 50 ML', categoria: 'Descartáveis', casa: 'MF - BETSY', fornecedor: 'Quality', unidade_compra: 'ml', tamanho_unidade: 50, preco_compra: 3.15, data_atualizacao: '27/07' },
  { nome: 'CORONA LONG NECK', categoria: 'Cerveja', casa: 'JT - FORTUNATO', fornecedor: 'AMBEV', unidade_compra: 'ml', tamanho_unidade: 330, preco_compra: 6.74, data_atualizacao: '27/07' },
  { nome: 'CORONA ZERO LONG NECK', categoria: 'Cerveja', casa: 'JT - FORTUNATO', fornecedor: 'AMBEV', unidade_compra: 'ml', tamanho_unidade: 330, preco_compra: 6.74, data_atualizacao: '27/07' },
  { nome: 'COSTELA GAÚCHA', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'EMPORIO TUIUTI', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 0, data_atualizacao: '27/07' },
  { nome: 'COSTELA SUINA SALGADA EXTRA', categoria: 'Outros', casa: 'JT - FORTUNATO', fornecedor: 'CORINGA', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 39.39, data_atualizacao: '27/07' },
  { nome: 'COXA C/ SOBRECOXA FRANGO', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'MEGA G', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 7.47, data_atualizacao: '27/07' },
  { nome: 'COXAO MOLE', categoria: 'Outros', casa: 'JT - FORTUNATO', fornecedor: 'MULTIFOODS', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 36.29, data_atualizacao: '27/07' },
  { nome: 'COXAO MOLE FUNCIONARIOS KG', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'MULTIFOODS', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 36.29, data_atualizacao: '27/07' },
  { nome: 'COXINHA ASA FRANGO', categoria: 'Outros', casa: 'JT - FORTUNATO', fornecedor: 'MULTIFOODS', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 10.99, data_atualizacao: '27/07' },
  { nome: 'COXINHA DE FRANGO', categoria: 'Outros', casa: 'JT - FORTUNATO', fornecedor: 'LEVI', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 2, data_atualizacao: '27/07' },
  { nome: 'CREME CROCANTE OVOMALTINE BISNAGA 900G', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'MEGA G', unidade_compra: 'g', tamanho_unidade: 900, preco_compra: 58.83, data_atualizacao: '27/07' },
  { nome: 'CREME DE LEITE 200GR 17%', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'AVELINOS', unidade_compra: 'g', tamanho_unidade: 200, preco_compra: 4.89, data_atualizacao: '27/07' },
  { nome: 'DESINFETANTE COALA', categoria: 'Limpeza', casa: 'MF - BETSY', fornecedor: 'Quality', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 15, data_atualizacao: '27/07' },
  { nome: 'DOCE DE LEITE 400G LA SERENISSIMA', categoria: 'Outros', casa: 'VMB - OLIVIO', fornecedor: 'DTK', unidade_compra: 'g', tamanho_unidade: 400, preco_compra: 14.2, data_atualizacao: '27/07' },
  { nome: 'DOMECQ CONHAQUE 1L', categoria: 'Vermute/Conhaque', casa: 'JT - FORTUNATO', fornecedor: 'SPON', unidade_compra: 'ml', tamanho_unidade: 1000, preco_compra: 25.9, data_atualizacao: '27/07' },
  { nome: 'EL JIMADOR BLANCO 750 ML', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'NSA DISTRIBUIDORA', unidade_compra: 'ml', tamanho_unidade: 750, preco_compra: 83.5, data_atualizacao: '27/07' },
  { nome: 'EMBALAGEM R-041 DIVISORIA BRANCA - REFLET', categoria: 'Outros', casa: 'JT - FORTUNATO', fornecedor: 'PLASTICOS SEGANTINI', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 2.98, data_atualizacao: '27/07' },
  { nome: 'ESPAGUETE GRANO DURO BARONIA N5', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'AVELINOS', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 6.29, data_atualizacao: '27/07' },
  { nome: 'ESPIRITO DE MINAS 700 ML', categoria: 'Outros', casa: 'JT - FORTUNATO', fornecedor: 'GENIUS/OFF/EASY/SKY', unidade_compra: 'ml', tamanho_unidade: 700, preco_compra: 61.5, data_atualizacao: '27/07' },
  { nome: 'ESPONJA DUPLA FACE', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'Quality', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 0.65, data_atualizacao: '27/07' },
  { nome: 'ESPONJA FIBRAÇO', categoria: 'Outros', casa: 'VMB - OLIVIO', fornecedor: 'Quality', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 1.6, data_atualizacao: '27/07' },
  { nome: 'FANTA GUARANA', categoria: 'Refrigerante', casa: 'VMB - OLIVIO', fornecedor: 'SPAL/FEMSA', unidade_compra: 'ml', tamanho_unidade: 350, preco_compra: 2.91, data_atualizacao: '27/07' },
  { nome: 'FANTA GUARANA ZERO', categoria: 'Refrigerante', casa: 'VMB - OLIVIO', fornecedor: 'SPAL/FEMSA', unidade_compra: 'ml', tamanho_unidade: 350, preco_compra: 2.91, data_atualizacao: '27/07' },
  { nome: 'FARINHA DE MANDIOCA FINA KG', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'KINGFOOD', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 4.92, data_atualizacao: '27/07' },
  { nome: 'FARINHA DE TRIGO PREMIUM ANACONDA', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'KINGFOOD', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 5.19, data_atualizacao: '27/07' },
  { nome: 'FARINHA PANKO ALFA KG', categoria: 'Outros', casa: 'VMB - OLIVIO', fornecedor: 'DTK', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 16.32, data_atualizacao: '27/07' },
  { nome: 'FEIJAO CARIOCA CAMIL 1KG', categoria: 'Outros', casa: 'VMB - OLIVIO', fornecedor: 'KINGFOOD', unidade_compra: 'g', tamanho_unidade: 1000, preco_compra: 9.29, data_atualizacao: '27/07' },
  { nome: 'FERMENTO EM PO QUIMICO 100G', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'AVELINOS', unidade_compra: 'g', tamanho_unidade: 100, preco_compra: 2.78, data_atualizacao: '27/07' },
  { nome: 'FILE FRANGO', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'MEGA G', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 14.77, data_atualizacao: '27/07' },
  { nome: 'FILE MIGNON EXTRA LIMPO', categoria: 'Outros', casa: 'JT - FORTUNATO', fornecedor: 'MULTIFOODS', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 84.99, data_atualizacao: '27/07' },
  { nome: 'FILE MIGNON RESFRIADO 5UP', categoria: 'Outros', casa: 'VMB - OLIVIO', fornecedor: 'MULTIFOODS', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 84.99, data_atualizacao: '27/07' },
  { nome: 'FILE SALMAO', categoria: 'Outros', casa: 'VMB - OLIVIO', fornecedor: 'MEGA G', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 70.69, data_atualizacao: '27/07' },
  { nome: 'FITA FILME 40CM', categoria: 'Descartáveis', casa: 'MF - BETSY', fornecedor: 'Quality', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 83.8, data_atualizacao: '27/07' },
  { nome: 'FRALDA RED PREMIUM', categoria: 'Outros', casa: 'JT - FORTUNATO', fornecedor: 'MINERVA', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 82, data_atualizacao: '27/07' },
  { nome: 'FUMACA LIQUIDA BOMBAY', categoria: 'Gin', casa: 'JT - FORTUNATO', fornecedor: 'SANTA VITA', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 0, data_atualizacao: '27/07' },
  { nome: 'GARRAFÃO VINHO BRANCO', categoria: 'Vinho/Espumante', casa: 'MF - BETSY', fornecedor: 'NSA DISTRIBUIDORA', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 41.9, data_atualizacao: '27/07' },
  { nome: 'GARRAFÃO VINHO TINTO', categoria: 'Vinho/Espumante', casa: 'MF - BETSY', fornecedor: 'NSA DISTRIBUIDORA', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 41.9, data_atualizacao: '27/07' },
  { nome: 'GAS CHOPP (m³)', categoria: 'Cerveja', casa: 'MF - BETSY', fornecedor: 'CRYSTALMIX', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 85.6, data_atualizacao: '27/07' },
  { nome: 'GELATO DE COOKIES AND CREAM 5L', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'ITALIAN', unidade_compra: 'ml', tamanho_unidade: 5000, preco_compra: 0, data_atualizacao: '27/07' },
  { nome: 'GELATO DE CREME 5L', categoria: 'Outros', casa: 'VMB - OLIVIO', fornecedor: 'ITALIAN', unidade_compra: 'ml', tamanho_unidade: 5000, preco_compra: 0, data_atualizacao: '27/07' },
  { nome: 'GELO 50MMX65MM', categoria: 'Outros', casa: 'VMB - OLIVIO', fornecedor: 'ICE 4 PROS', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 2.17, data_atualizacao: '27/07' },
  { nome: 'GEMA OVO PASTEURIZADA', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'AVELINOS', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 38.9, data_atualizacao: '27/07' },
  { nome: 'GERGELIM BRANCO', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'KINGFOOD', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 16.62, data_atualizacao: '27/07' },
  { nome: 'GERGELIM PRETO', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'KINGFOOD', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 31, data_atualizacao: '27/07' },
  { nome: 'GIN FORDS LONDON DRY 750ML', categoria: 'Gin', casa: 'MF - BETSY', fornecedor: 'NSA DISTRIBUIDORA', unidade_compra: 'ml', tamanho_unidade: 750, preco_compra: 67.35, data_atualizacao: '27/07' },
  { nome: 'GNOCCHI MANDIOQUINHA', categoria: 'Outros', casa: 'VMB - OLIVIO', fornecedor: 'ER MASSA', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 31.99, data_atualizacao: '27/07' },
  { nome: 'GORDURA VEGETAL COAMO 15,8L', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'MULTIFOODS', unidade_compra: 'ml', tamanho_unidade: 15800, preco_compra: 158.99, data_atualizacao: '27/07' },
  { nome: 'GUARANA ANTARCTICA', categoria: 'Refrigerante', casa: 'ESCRITORIO', fornecedor: 'MALTE', unidade_compra: 'ml', tamanho_unidade: 350, preco_compra: 3.09, data_atualizacao: '28/07' },
  { nome: 'GUARANA ZERO ANTARCTICA', categoria: 'Refrigerante', casa: 'ESCRITORIO', fornecedor: 'MALTE', unidade_compra: 'ml', tamanho_unidade: 350, preco_compra: 3.09, data_atualizacao: '28/07' },
  { nome: 'GUARDANAPO 40X40', categoria: 'Descartáveis', casa: 'MF - BETSY', fornecedor: 'SCALA', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 0, data_atualizacao: '27/07' },
  { nome: 'H2OH LIMONETO', categoria: 'Outros', casa: 'ESCRITORIO', fornecedor: 'MALTE', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 4.79, data_atualizacao: '28/07' },
  { nome: 'HAMBURGUER DE WAGYU 150G CX 3,6KG', categoria: 'Outros', casa: 'JT - FORTUNATO', fornecedor: 'WESSEL', unidade_compra: 'g', tamanho_unidade: 3600, preco_compra: 89, data_atualizacao: '27/07' },
  { nome: 'HEINEKEN LONG NECK', categoria: 'Cerveja', casa: 'VMB - OLIVIO', fornecedor: 'HNK', unidade_compra: 'ml', tamanho_unidade: 330, preco_compra: 6.55, data_atualizacao: '27/07' },
  { nome: 'IÇA BEER IPA 600ML', categoria: 'Cerveja', casa: 'JT - FORTUNATO', fornecedor: 'IÇA BEER CERVEJARIA', unidade_compra: 'ml', tamanho_unidade: 600, preco_compra: 17.9, data_atualizacao: '27/07' },
  { nome: 'IOGURTE NATURAL COPO 150G', categoria: 'Descartáveis', casa: 'VMB - OLIVIO', fornecedor: 'AVELINOS', unidade_compra: 'g', tamanho_unidade: 150, preco_compra: 3.3, data_atualizacao: '27/07' },
  { nome: 'JACK DANIEL´S 1L', categoria: 'Outros', casa: 'VMB - OLIVIO', fornecedor: 'FG7 (PERNOD)', unidade_compra: 'ml', tamanho_unidade: 1000, preco_compra: 114.9, data_atualizacao: '27/07' },
  { nome: 'JIM BEAN WHITE 1L', categoria: 'Outros', casa: 'JT - FORTUNATO', fornecedor: 'GRF', unidade_compra: 'ml', tamanho_unidade: 1000, preco_compra: 63.9, data_atualizacao: '27/07' },
  { nome: 'LEITE CONDENSADO 2,6KG (MOÇA)', categoria: 'Outros', casa: 'VMB - OLIVIO', fornecedor: 'KINGFOOD', unidade_compra: 'g', tamanho_unidade: 2600, preco_compra: 69.99, data_atualizacao: '27/07' },
  { nome: 'LEITE INTEGRAL UHT 1L', categoria: 'Outros', casa: 'VMB - OLIVIO', fornecedor: 'KINGFOOD', unidade_compra: 'ml', tamanho_unidade: 1000, preco_compra: 5.59, data_atualizacao: '27/07' },
  { nome: 'LICOR 43 CHOCOLATE 700ML', categoria: 'Licor/Aperitivo', casa: 'JT - FORTUNATO', fornecedor: 'NORONHA', unidade_compra: 'ml', tamanho_unidade: 700, preco_compra: 149.83, data_atualizacao: '27/07' },
  { nome: 'LIMPA PEDRA', categoria: 'Outros', casa: 'JT - FORTUNATO', fornecedor: 'Quality', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 21, data_atualizacao: '27/07' },
  { nome: 'LINGUICA CALABRESA FINA', categoria: 'Outros', casa: 'JT - FORTUNATO', fornecedor: 'BIAGIO', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 46, data_atualizacao: '27/07' },
  { nome: 'LINGUICA FINA QUEIJO E OREGANO 400G', categoria: 'Outros', casa: 'JT - FORTUNATO', fornecedor: 'BIAGIO', unidade_compra: 'g', tamanho_unidade: 400, preco_compra: 50, data_atualizacao: '27/07' },
  { nome: 'LINGUICA TOSCANA AURORA', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'MEGA G', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 17.06, data_atualizacao: '27/07' },
  { nome: 'LULA P BABY', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'KHADUN', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 0, data_atualizacao: '27/07' },
  { nome: 'LUVA (LÁTEX - PROCEDIMENTO)', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'Quality', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 30.2, data_atualizacao: '27/07' },
  { nome: 'MACARRAO RIGATONE BARILLA', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'DTK', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 10.24, data_atualizacao: '27/07' },
  { nome: 'MACARRAO SPAGHETTONI N7 BARILLA', categoria: 'Outros', casa: 'JT - FORTUNATO', fornecedor: 'DTK', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 9.54, data_atualizacao: '27/07' },
  { nome: 'MANDIOCA CONGELADA SUPREME', categoria: 'Outros', casa: 'JT - FORTUNATO', fornecedor: 'SEARA', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 0, data_atualizacao: '27/07' },
  { nome: 'MANTEIGA SEM SAL BLOCO 5KG', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'MEGA G', unidade_compra: 'g', tamanho_unidade: 5000, preco_compra: 33.67, data_atualizacao: '27/07' },
  { nome: 'MARACUJA POLPA', categoria: 'Suco', casa: 'MF - BETSY', fornecedor: 'BABYFRUIT', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 0, data_atualizacao: '27/07' },
  { nome: 'MARSHMALLOW BRANCO', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'SANTA VITA', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 0, data_atualizacao: '27/07' },
  { nome: 'MASSA DE PASTEL', categoria: 'Outros', casa: 'VMB - OLIVIO', fornecedor: 'FAVORITA', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 0, data_atualizacao: '27/07' },
  { nome: 'MASSA FOLHADA KG', categoria: 'Outros', casa: 'VMB - OLIVIO', fornecedor: 'AVELINOS', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 35.4, data_atualizacao: '27/07' },
  { nome: 'MEL ISIS POTE 1KG', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'KINGFOOD', unidade_compra: 'g', tamanho_unidade: 1000, preco_compra: 36.88, data_atualizacao: '27/07' },
  { nome: 'MOCOTO BOVINO', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'ROYALMEAT', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 19.9, data_atualizacao: '27/07' },
  { nome: 'MOLHO SHOYU SAKURA 1 L', categoria: 'Outros', casa: 'VMB - OLIVIO', fornecedor: 'AVELINOS', unidade_compra: 'ml', tamanho_unidade: 1000, preco_compra: 15.6, data_atualizacao: '27/07' },
  { nome: 'MOSTARDA A LANCIENNE MAILLE 1kg', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'KINGFOOD', unidade_compra: 'g', tamanho_unidade: 1000, preco_compra: 62.7, data_atualizacao: '27/07' },
  { nome: 'MOSTARDA DIJON MAILLE 865G', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'KINGFOOD', unidade_compra: 'g', tamanho_unidade: 865, preco_compra: 69.9, data_atualizacao: '27/07' },
  { nome: 'MOSTARDA GALAO CEPERA', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'DTK', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 23.99, data_atualizacao: '27/07' },
  { nome: 'NEGRESCO TRITURADO', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'DTK', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 43.85, data_atualizacao: '27/07' },
  { nome: 'NIB BITTER', categoria: 'Xarope/Bitter', casa: 'JT - FORTUNATO', fornecedor: 'SPON', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 69.9, data_atualizacao: '27/07' },
  { nome: 'NOZES SEM CASCA 1KG', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'KINGFOOD', unidade_compra: 'g', tamanho_unidade: 1000, preco_compra: 49.98, data_atualizacao: '27/07' },
  { nome: 'NUTELLA POTE 3KG', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'AVELINOS', unidade_compra: 'g', tamanho_unidade: 3000, preco_compra: 187.25, data_atualizacao: '27/07' },
  { nome: 'OLEO DE ALGODAO BLD 15L LIZA', categoria: 'Outros', casa: 'JT - FORTUNATO', fornecedor: 'AVELINOS', unidade_compra: 'ml', tamanho_unidade: 15000, preco_compra: 195, data_atualizacao: '27/07' },
  { nome: 'OLEO DE SOJA 900ML', categoria: 'Outros', casa: 'VMB - OLIVIO', fornecedor: 'KINGFOOD', unidade_compra: 'ml', tamanho_unidade: 900, preco_compra: 6.98, data_atualizacao: '27/07' },
  { nome: 'OSSO COM TUTANO', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'ROYALMEAT', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 13.9, data_atualizacao: '27/07' },
  { nome: 'OVOMALTINE FLOCOS', categoria: 'Outros', casa: 'VMB - OLIVIO', fornecedor: 'MEGA G', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 38.05, data_atualizacao: '27/07' },
  { nome: 'OXIDO NITROSO', categoria: 'Outros', casa: 'VMB - OLIVIO', fornecedor: 'CRYSTALMIX', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 219, data_atualizacao: '27/07' },
  { nome: 'PAO BRIOCHE FORMA BELLLNAY UN', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'BELLNAY', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 25, data_atualizacao: '27/07' },
  { nome: 'PAO DE FORMA P FUNCIONARIOS', categoria: 'Outros', casa: 'VMB - OLIVIO', fornecedor: 'AVELINOS', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 5.99, data_atualizacao: '27/07' },
  { nome: 'PAO DE HAMBURGUER', categoria: 'Outros', casa: 'VMB - OLIVIO', fornecedor: 'BELLNAY', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 2.75, data_atualizacao: '27/07' },
  { nome: 'PAO MINI HAMBURGUER', categoria: 'Outros', casa: 'VMB - OLIVIO', fornecedor: 'BELLNAY', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 1.5, data_atualizacao: '27/07' },
  { nome: 'PAPEL ALUMINIO', categoria: 'Descartáveis', casa: 'MF - BETSY', fornecedor: 'Quality', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 60, data_atualizacao: '27/07' },
  { nome: 'PAPEL HIGIENICO CAI CAI', categoria: 'Descartáveis', casa: 'JT - FORTUNATO', fornecedor: 'Amade', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 200.71, data_atualizacao: '27/07' },
  { nome: 'PAPEL TOALHA INTERFOLHADO', categoria: 'Descartáveis', casa: 'MF - BETSY', fornecedor: 'Amade', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 191.61, data_atualizacao: '27/07' },
  { nome: 'PAPEL TOALHA ROLAO', categoria: 'Descartáveis', casa: 'MF - BETSY', fornecedor: 'Amade', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 256, data_atualizacao: '27/07' },
  { nome: 'PEPINO EM CONSERVA BLD 2KG', categoria: 'Outros', casa: 'JT - FORTUNATO', fornecedor: 'MULTIFOODS', unidade_compra: 'g', tamanho_unidade: 2000, preco_compra: 28.99, data_atualizacao: '27/07' },
  { nome: 'PESCADA AMARELA KG', categoria: 'Outros', casa: 'VMB - OLIVIO', fornecedor: 'FRESCATO', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 0, data_atualizacao: '27/07' },
  { nome: 'PICANHA PREMIUM', categoria: 'Outros', casa: 'JT - FORTUNATO', fornecedor: 'MULTIFOODS', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 88.99, data_atualizacao: '27/07' },
  { nome: 'POLENTINA QUAKER 500G', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'AVELINOS', unidade_compra: 'g', tamanho_unidade: 500, preco_compra: 4.83, data_atualizacao: '27/07' },
  { nome: 'POLPA ABACAXI', categoria: 'Suco', casa: 'JT - FORTUNATO', fornecedor: 'BABYFRUIT', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 0, data_atualizacao: '27/07' },
  { nome: 'POLPA FRUTAS VERMELHAS', categoria: 'Suco', casa: 'JT - FORTUNATO', fornecedor: 'BABYFRUIT', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 0, data_atualizacao: '27/07' },
  { nome: 'POLPA MORANGO', categoria: 'Suco', casa: 'JT - FORTUNATO', fornecedor: 'BABYFRUIT', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 0, data_atualizacao: '27/07' },
  { nome: 'PRESUNTO PARMA PEÇA 7KG', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'CASA FLORA', unidade_compra: 'g', tamanho_unidade: 7000, preco_compra: 0, data_atualizacao: '27/07' },
  { nome: 'PROSSECO AURORA', categoria: 'Vinho/Espumante', casa: 'JT - FORTUNATO', fornecedor: 'GRF', unidade_compra: 'ml', tamanho_unidade: 750, preco_compra: 28.5, data_atualizacao: '27/07' },
  { nome: 'QUEIJO BRIE QUATA', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'MULTIFOODS', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 56.99, data_atualizacao: '27/07' },
  { nome: 'QUEIJO GORGONZOLA QUATA', categoria: 'Outros', casa: 'VMB - OLIVIO', fornecedor: 'MULTIFOODS', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 57.49, data_atualizacao: '27/07' },
  { nome: 'QUEIJO MEIA CURA KG', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'MEGA G', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 85.18, data_atualizacao: '27/07' },
  { nome: 'QUEIJO MUSSARELA DE BUFALA CAPRESE', categoria: 'Outros', casa: 'JT - FORTUNATO', fornecedor: 'LEVITARE', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 62, data_atualizacao: '27/07' },
  { nome: 'QUEIJO MUSSARELA SCALA', categoria: 'Outros', casa: 'VMB - OLIVIO', fornecedor: 'MEGA G', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 47.37, data_atualizacao: '27/07' },
  { nome: 'QUEIJO PARMESAO TIROLEZ KG', categoria: 'Outros', casa: 'VMB - OLIVIO', fornecedor: 'MEGA G', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 75.92, data_atualizacao: '27/07' },
  { nome: 'QUEIJO PRATO SCALA', categoria: 'Outros', casa: 'VMB - OLIVIO', fornecedor: 'MEGA G', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 52.57, data_atualizacao: '27/07' },
  { nome: 'RED BULL REGULAR', categoria: 'Refrigerante', casa: 'JT - FORTUNATO', fornecedor: 'FRONT (PERNOD)', unidade_compra: 'ml', tamanho_unidade: 250, preco_compra: 7.99, data_atualizacao: '27/07' },
  { nome: 'RED BULL SUGAR FREE', categoria: 'Refrigerante', casa: 'JT - FORTUNATO', fornecedor: 'FRONT (PERNOD)', unidade_compra: 'ml', tamanho_unidade: 250, preco_compra: 7.99, data_atualizacao: '27/07' },
  { nome: 'REFIL P/ ASSENTO SANITARIO', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'Amade', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 14.9, data_atualizacao: '27/07' },
  { nome: 'REQUEIJAO BISNAGA SCALA 1,5', categoria: 'Outros', casa: 'VMB - OLIVIO', fornecedor: 'MULTIFOODS', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 43.49, data_atualizacao: '27/07' },
  { nome: 'SABAO DAYMON - MASTER DISH 5LT', categoria: 'Limpeza', casa: 'MF - BETSY', fornecedor: 'Daymon', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 167.08, data_atualizacao: '27/07' },
  { nome: 'SACO DE LIXO PRETO REFORÇADO 100L', categoria: 'Descartáveis', casa: 'MF - BETSY', fornecedor: 'SPEEDLOG', unidade_compra: 'ml', tamanho_unidade: 100000, preco_compra: 39.9, data_atualizacao: '27/07' },
  { nome: 'SACO DE LIXO PRETO REFORÇADO 200L', categoria: 'Descartáveis', casa: 'MF - BETSY', fornecedor: 'SPEEDLOG', unidade_compra: 'ml', tamanho_unidade: 200000, preco_compra: 71.9, data_atualizacao: '27/07' },
  { nome: 'SACO DE LIXO VERDE REFORÇADO 100L', categoria: 'Descartáveis', casa: 'MF - BETSY', fornecedor: 'SPEEDLOG', unidade_compra: 'ml', tamanho_unidade: 100000, preco_compra: 39.9, data_atualizacao: '27/07' },
  { nome: 'SACO DE LIXO VERDE REFORÇADO 200L', categoria: 'Descartáveis', casa: 'VMB - OLIVIO', fornecedor: 'SPEEDLOG', unidade_compra: 'ml', tamanho_unidade: 200000, preco_compra: 71.9, data_atualizacao: '27/07' },
  { nome: 'SACO DE LIXO VERDE REFORÇADO 60L', categoria: 'Descartáveis', casa: 'MF - BETSY', fornecedor: 'SPEEDLOG', unidade_compra: 'ml', tamanho_unidade: 60000, preco_compra: 18.9, data_atualizacao: '27/07' },
  { nome: 'SACO PARA CONFEITAR 50x38cm GG', categoria: 'Descartáveis', casa: 'MF - BETSY', fornecedor: 'Quality', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 69.9, data_atualizacao: '27/07' },
  { nome: 'SACO VACUO 15X20', categoria: 'Descartáveis', casa: 'MF - BETSY', fornecedor: 'Tecmaq', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 217, data_atualizacao: '27/07' },
  { nome: 'SACO VACUO 25X30', categoria: 'Descartáveis', casa: 'MF - BETSY', fornecedor: 'Tecmaq', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 537, data_atualizacao: '27/07' },
  { nome: 'SACO/PANO ALVEJADO', categoria: 'Descartáveis', casa: 'JT - FORTUNATO', fornecedor: 'Quality', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 2.7, data_atualizacao: '27/07' },
  { nome: 'SAINT PETER CONGELADO', categoria: 'Outros', casa: 'JT - FORTUNATO', fornecedor: 'MEGA G', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 55.29, data_atualizacao: '27/07' },
  { nome: 'SAKE AZUMA KIRIN SOFT 740 ML', categoria: 'Outros', casa: 'JT - FORTUNATO', fornecedor: 'NORONHA', unidade_compra: 'ml', tamanho_unidade: 740, preco_compra: 23.8, data_atualizacao: '27/07' },
  { nome: 'SAKE GEKKEIKAN 750 ML', categoria: 'Outros', casa: 'JT - FORTUNATO', fornecedor: 'GENIUS/OFF/EASY/SKY', unidade_compra: 'ml', tamanho_unidade: 750, preco_compra: 65.9, data_atualizacao: '27/07' },
  { nome: 'SAL REFINADO', categoria: 'Outros', casa: 'VMB - OLIVIO', fornecedor: 'MEGA G', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 2.21, data_atualizacao: '27/07' },
  { nome: 'SALSA TRUFADA', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'EMPORIO TARTUFI', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 150, data_atualizacao: '27/07' },
  { nome: 'SELETA 600 ML', categoria: 'Cachaça', casa: 'JT - FORTUNATO', fornecedor: 'FG7 (PERNOD)', unidade_compra: 'ml', tamanho_unidade: 600, preco_compra: 31.21, data_atualizacao: '27/07' },
  { nome: 'SEU GIN PREMIUM 1750ML', categoria: 'Gin', casa: 'JT - FORTUNATO', fornecedor: 'SEU GIN', unidade_compra: 'ml', tamanho_unidade: 1750, preco_compra: 55.71, data_atualizacao: '27/07' },
  { nome: 'SPAR CLEAN DESINFETANTE EUCALIPTO 5L', categoria: 'Limpeza', casa: 'MF - BETSY', fornecedor: 'SPAR CLEAN', unidade_compra: 'ml', tamanho_unidade: 5000, preco_compra: 0, data_atualizacao: '27/07' },
  { nome: 'SPRITE', categoria: 'Refrigerante', casa: 'ESCRITORIO', fornecedor: 'MALTE', unidade_compra: 'ml', tamanho_unidade: 350, preco_compra: 3.59, data_atualizacao: '28/07' },
  { nome: 'SPRITE LEMON FRESH PET 510ML', categoria: 'Outros', casa: 'JT - FORTUNATO', fornecedor: 'SPAL/FEMSA', unidade_compra: 'ml', tamanho_unidade: 510, preco_compra: 2.72, data_atualizacao: '27/07' },
  { nome: 'SPRITE ZERO', categoria: 'Refrigerante', casa: 'ESCRITORIO', fornecedor: 'MALTE', unidade_compra: 'ml', tamanho_unidade: 350, preco_compra: 3.69, data_atualizacao: '28/07' },
  { nome: 'STELLA ARTOIS LONG NECK', categoria: 'Cerveja', casa: 'JT - FORTUNATO', fornecedor: 'AMBEV', unidade_compra: 'ml', tamanho_unidade: 330, preco_compra: 6.3, data_atualizacao: '27/07' },
  { nome: 'STELLA ARTOIS SEM GLUTEN 330ML', categoria: 'Cerveja', casa: 'JT - FORTUNATO', fornecedor: 'AMBEV', unidade_compra: 'ml', tamanho_unidade: 330, preco_compra: 6.78, data_atualizacao: '27/07' },
  { nome: 'STONE DET - DAYMON', categoria: 'Outros', casa: 'VMB - OLIVIO', fornecedor: 'Daymon', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 356.44, data_atualizacao: '27/07' },
  { nome: 'SUCO CONCENTRADO MANGA MAGUARY 500ML', categoria: 'Suco', casa: 'MF - BETSY', fornecedor: 'KINGFOOD', unidade_compra: 'ml', tamanho_unidade: 500, preco_compra: 5.99, data_atualizacao: '27/07' },
  { nome: 'SUCO DE UVA BRANCO', categoria: 'Suco', casa: 'MF - BETSY', fornecedor: 'SANTA VITA', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 0, data_atualizacao: '27/07' },
  { nome: 'SUSPIRO', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'SANTA VITA', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 0, data_atualizacao: '27/07' },
  { nome: 'TOMATE PELADO INTEIRO OLE 2,5KG', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'MEGA G', unidade_compra: 'g', tamanho_unidade: 2500, preco_compra: 29.99, data_atualizacao: '27/07' },
  { nome: 'TOMATE PELADO ITALIANO 2,5KG', categoria: 'Outros', casa: 'JT - FORTUNATO', fornecedor: 'MEGA G', unidade_compra: 'g', tamanho_unidade: 2500, preco_compra: 32.9, data_atualizacao: '27/07' },
  { nome: 'VELA FAISCA', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'MERCADO LIVRE', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 0, data_atualizacao: '27/07' },
  { nome: 'VELA VULCÃO', categoria: 'Outros', casa: 'MF - BETSY', fornecedor: 'SANTA VITA', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 0, data_atualizacao: '27/07' },
  { nome: 'VELHO BARREIRO 910 ML', categoria: 'Cachaça', casa: 'JT - FORTUNATO', fornecedor: 'MDG (PERNOD)', unidade_compra: 'ml', tamanho_unidade: 910, preco_compra: 14.78, data_atualizacao: '27/07' },
  { nome: 'VINHO BRANCO BAG', categoria: 'Vinho/Espumante', casa: 'JT - FORTUNATO', fornecedor: 'NORONHA', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 57.53, data_atualizacao: '27/07' },
  { nome: 'XAROPE AMORA 1883', categoria: 'Xarope/Bitter', casa: 'MF - BETSY', fornecedor: 'FG7 (PERNOD)', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 63.92, data_atualizacao: '27/07' },
  { nome: 'XAROPE BLUE CURACAU 1883', categoria: 'Xarope/Bitter', casa: 'MF - BETSY', fornecedor: 'FG7 (PERNOD)', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 63.92, data_atualizacao: '27/07' },
  { nome: 'XAROPE COCO MONIN', categoria: 'Xarope/Bitter', casa: 'JT - FORTUNATO', fornecedor: 'GENIUS/OFF/EASY/SKY', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 46.6, data_atualizacao: '27/07' },
  { nome: 'XAROPE FABBRI FRAMBOESA', categoria: 'Xarope/Bitter', casa: 'JT - FORTUNATO', fornecedor: 'FG7 (PERNOD)', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 69.99, data_atualizacao: '27/07' },
  { nome: 'XAROPE MAÇA VERDE 1883', categoria: 'Xarope/Bitter', casa: 'MF - BETSY', fornecedor: 'FG7 (PERNOD)', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 63.92, data_atualizacao: '27/07' },
  { nome: 'XAROPE MORANGO 1883', categoria: 'Hortifruti', casa: 'MF - BETSY', fornecedor: 'FG7 (PERNOD)', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 63.92, data_atualizacao: '27/07' },
  { nome: 'XAROPE TANGERINA MONIN', categoria: 'Xarope/Bitter', casa: 'MF - BETSY', fornecedor: 'NSA DISTRIBUIDORA', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 47.85, data_atualizacao: '27/07' },
  { nome: 'XAROPE TORANJA', categoria: 'Xarope/Bitter', casa: 'JT - FORTUNATO', fornecedor: 'GENIUS/OFF/EASY/SKY', unidade_compra: 'unidade', tamanho_unidade: 1, preco_compra: 46.6, data_atualizacao: '27/07' },
];
